# Backpropagation Classification with Keras

In [23]:
import numpy as np
import pandas as pd


In [24]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa', 'profile_score', 'placed'])

In [25]:
df.head()

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [26]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [27]:
model = Sequential()

In [28]:
model.add(Dense(2,activation='sigmoid',input_dim=2))
model.add(Dense(1,activation='sigmoid'))

In [29]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 2)                 6         
                                                                 
 dense_7 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [30]:
model.get_weights()

[array([[ 1.172186  ,  0.19506085],
        [ 0.23292875, -0.01958454]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.6998066],
        [-1.0406903]], dtype=float32),
 array([0.], dtype=float32)]

In [31]:
new_weights = [np.array([[0.1  ,0.1],
        [ 0.1, 0.1]], dtype=np.float32),
 np.array([0., 0.], dtype=np.float32),
 np.array([[0.1],
        [0.1]], dtype=np.float32),
 np.array([0.], dtype=np.float32)]

In [32]:
model.set_weights(new_weights)

In [33]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [34]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy',optimizer=optimizer)

In [38]:
model.fit(df.iloc[:,0:-1].values,df['placed'].values,epochs=15,verbose=1,batch_size=1)

Epoch 1/15
4/4 [==============================] - 0s 2ms/step - loss: 0.6922
Epoch 2/15
4/4 [==============================] - 0s 2ms/step - loss: 0.6923
Epoch 3/15
4/4 [==============================] - 0s 2ms/step - loss: 0.6922
Epoch 4/15
4/4 [==============================] - 0s 3ms/step - loss: 0.6922
Epoch 5/15
4/4 [==============================] - 0s 2ms/step - loss: 0.6922
Epoch 6/15
4/4 [==============================] - 0s 2ms/step - loss: 0.6922
Epoch 7/15
4/4 [==============================] - 0s 1ms/step - loss: 0.6923
Epoch 8/15
4/4 [==============================] - 0s 2ms/step - loss: 0.6922
Epoch 9/15
4/4 [==============================] - 0s 2ms/step - loss: 0.6922
Epoch 10/15
4/4 [==============================] - 0s 1ms/step - loss: 0.6921
Epoch 11/15
4/4 [==============================] - 0s 2ms/step - loss: 0.6922
Epoch 12/15
4/4 [==============================] - 0s 2ms/step - loss: 0.6923
Epoch 13/15
4/4 [==============================] - 0s 2ms/step - loss: 0.