# Backpropagation Regression with Keras

In [44]:
import numpy as np
import pandas as pd


In [45]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [46]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [47]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [48]:
model = Sequential()

In [49]:
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

In [50]:
model.summary()


Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 2)                 6         
                                                                 
 dense_7 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [51]:
model.get_weights()

[array([[-0.430066  , -0.3381111 ],
        [ 0.50166893, -1.1173279 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.31274545],
        [-1.0103467 ]], dtype=float32),
 array([0.], dtype=float32)]

In [52]:
new_weights = [np.array([[0.1  ,0.1],
        [ 0.1, 0.1]], dtype=np.float32),
 np.array([0., 0.], dtype=np.float32),
 np.array([[0.1],
        [0.1]], dtype=np.float32),
 np.array([0.], dtype=np.float32)]

In [53]:
model.set_weights(new_weights)

In [54]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [55]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [56]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=100,verbose=1,batch_size=1)

Epoch 1/100


4/4 [==============================] - 0s 2ms/step - loss: 27.9023
Epoch 2/100
4/4 [==============================] - 0s 1ms/step - loss: 27.5848
Epoch 3/100
4/4 [==============================] - 0s 2ms/step - loss: 27.2557
Epoch 4/100
4/4 [==============================] - 0s 3ms/step - loss: 26.9005
Epoch 5/100
4/4 [==============================] - 0s 2ms/step - loss: 26.5708
Epoch 6/100
4/4 [==============================] - 0s 2ms/step - loss: 26.2003
Epoch 7/100
4/4 [==============================] - 0s 3ms/step - loss: 25.8201
Epoch 8/100
4/4 [==============================] - 0s 2ms/step - loss: 25.4560
Epoch 9/100
4/4 [==============================] - 0s 1ms/step - loss: 25.0881
Epoch 10/100
4/4 [==============================] - 0s 3ms/step - loss: 24.6481
Epoch 11/100
4/4 [==============================] - 0s 2ms/step - loss: 24.2277
Epoch 12/100
4/4 [==============================] - 0s 3ms/step - loss: 23.8381
Epoch 13/100
4/4 [==============================] - 0s 2ms/st

In [57]:
model.get_weights()

[array([[0.38434047, 0.38434047],
        [0.390983  , 0.390983  ]], dtype=float32),
 array([0.29191026, 0.29191026], dtype=float32),
 array([[0.39341325],
        [0.39341325]], dtype=float32),
 array([0.21576247], dtype=float32)]