# Customer Churn Prediction

In [151]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


In [152]:
df = pd.read_csv(r'D:\copy of htdocs\practice\Python\200days\Day174 Customer Churn Prediction\Churn_Modelling.csv')

In [153]:
df.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [154]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [155]:
df.duplicated().sum()

0

In [156]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [157]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [158]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [159]:
df.drop(columns=['RowNumber','CustomerId','Surname'],inplace=True)

In [160]:
df.head()

CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [161]:
df=pd.get_dummies(df,columns=['Geography','Gender'],drop_first=True)

In [162]:
from sklearn.model_selection import train_test_split


In [163]:
X=df.drop(columns=['Exited'])
y = df['Exited']


In [164]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [165]:
X_train.shape

(8000, 11)

In [166]:
X.head()

CreditScore  Age  Tenure  ...  Geography_Germany  Geography_Spain  Gender_Male
0          619   42       2  ...              False            False        False
1          608   41       1  ...              False             True        False
2          502   42       8  ...              False            False        False
3          699   39       1  ...              False            False        False
4          850   43       2  ...              False             True        False

[5 rows x 11 columns]

In [167]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [168]:
from sklearn.preprocessing import StandardScaler


In [169]:
scalar = StandardScaler()

In [170]:
X_train_scaled = scalar.fit_transform(X_train)
X_test_scaled = scalar.transform(X_test)

In [171]:
X_train_scaled

array([[-0.23082038, -0.94449979, -0.70174202, ...,  1.71490137,
        -0.57273139,  0.91509065],
       [-0.25150912, -0.94449979, -0.35520275, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [-0.3963303 ,  0.77498705,  0.33787579, ...,  1.71490137,
        -0.57273139, -1.09278791],
       ...,
       [ 0.22433188,  0.58393295,  1.3774936 , ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 0.13123255,  0.01077067,  1.03095433, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 1.1656695 ,  0.29735181,  0.33787579, ...,  1.71490137,
        -0.57273139,  0.91509065]])

In [172]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import  Sequential
from tensorflow.keras.layers import Dense

In [173]:
model = Sequential()

In [174]:
model.add(Dense(3,activation='sigmoid',input_dim=11))

In [175]:
model.add(Dense(1,activation='sigmoid'))

In [176]:
model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_17 (Dense)            (None, 3)                 36        
                                                                 
 dense_18 (Dense)            (None, 1)                 4         
                                                                 
Total params: 40 (160.00 Byte)
Trainable params: 40 (160.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [177]:
model.compile(loss='binary_crossentropy',optimizer='Adam')

In [178]:
model.fit(X_train_scaled,y_train,epochs=10)

Epoch 1/10


250/250 [==============================] - 1s 964us/step - loss: 0.5221
Epoch 2/10
250/250 [==============================] - 0s 876us/step - loss: 0.4885
Epoch 3/10
250/250 [==============================] - 0s 871us/step - loss: 0.4680
Epoch 4/10
250/250 [==============================] - 0s 990us/step - loss: 0.4543
Epoch 5/10
250/250 [==============================] - 0s 1ms/step - loss: 0.4452
Epoch 6/10
250/250 [==============================] - 0s 956us/step - loss: 0.4389
Epoch 7/10
250/250 [==============================] - 0s 888us/step - loss: 0.4344
Epoch 8/10
250/250 [==============================] - 0s 908us/step - loss: 0.4311
Epoch 9/10
250/250 [==============================] - 0s 888us/step - loss: 0.4286
Epoch 10/10
250/250 [==============================] - 0s 888us/step - loss: 0.4265


In [179]:
model.layers[0].get_weights()

[array([[ 0.174574  , -0.23780404,  0.1024153 ],
        [-1.9314271 , -0.45406958, -0.8941649 ],
        [-0.19349636,  0.45051005,  0.3322523 ],
        [-0.23344517, -0.61946917, -0.07658976],
        [-0.17419118,  1.0819904 , -0.00193656],
        [ 0.12336582, -0.03145882,  0.00791727],
        [ 0.4139227 ,  0.7918871 ,  1.2576658 ],
        [-0.15761048,  0.23415016, -0.10160626],
        [-0.350563  , -0.2560709 , -0.88725317],
        [ 0.16728881,  0.06052941, -0.33450645],
        [ 0.1456385 ,  0.78975594,  0.7498202 ]], dtype=float32),
 array([0.17089693, 0.19132172, 0.20411967], dtype=float32)]

In [180]:
model.layers[1].get_weights()

[array([[-1.8390592 ],
        [-0.79279447],
        [-0.57149076]], dtype=float32),
 array([0.072137], dtype=float32)]

In [181]:
y_log = model.predict(X_test_scaled)


 1/63 [..............................] - ETA: 2s

63/63 [==============================] - 0s 1ms/step


In [182]:
y_pred=np.where(y_log>0.5,1,0)

In [183]:
from sklearn.metrics import accuracy_score

In [184]:
accuracy_score(y_test,y_pred)

0.8